### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by gingerbeardman** [schriftgestalt/BDFFileFormat#1]
Thanks for recent changes, but still an issue.

```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 280, in writeFont_error_
  File "plugin.py", line 72, in export
    self.writeGlyphs(font, f)
  File "plugin.py", line 185, in writeGlyphs
    self.writeGlyph(g, file)
  File "plugin.py", line 157, in writeGlyph
    if len(glyph.unicode) >=4:
TypeError: object of type 'NoneType' has no len()
```

Example glyphs file exported from Fontstruct:
[becker_bold.glyphs.zip](https://github.com/schriftgestalt/BDFFileFormat/files/4591825/becker_bold.glyphs.zip)

**Comment by schriftgestalt** [comment]
Thanks for the file. 
I improved the plugin a bit. 

Two things you need to change in the file:
The plugin expects the pixel glyph to be called "pixel". So best rename the glyph. Then you also can use the pixel tool (that would need a bit more work as the pixel components scaled). 

And you need to set the grid. It need the grid to calculate the pixel size.

**Comment by gingerbeardman** [comment]
Thanks!

Regarding changes needed to the file: I'm sorry but this file is exported untouched from Fontstruct.

- So, shall I request these changes be made to the export format at Fontstruct? 
- Or should you request them (given Glyphs is the only supported export format and you are a listed Sponsor of Fontstruct)? 
- Or do I misunderstand the changes required?

**Comment by schriftgestalt** [comment]
You can do the changed very quick in Glyphs. 

I forgot to add that I added a way to configure the "pixel". In Font Info > Font, add a custom parameter "BDFpixel" and as the value use the name of the pixel glyph (in this case: "brick-1"). 

And the grid is set in Font Info > Other settings. Use 170 for Grid Spacing.

**Comment by gingerbeardman** [comment]
Thanks! I'll do that to test.

Ideally, the Fontstruct export should work without any changes required by the user.

**Comment by gingerbeardman** [comment]
Sadly my test after those changes still does not result in a valid BDF file.

Same error. BDF bitmap data is just zeroes.

**Comment by robmeek** [comment]
@gingerbeardman Have you considered parsing the .glyphs file and generating the BDF directly with a little CLI utility – maybe it would be a quicker route for you? I’m almost tempted to do it myself.

**Comment by gingerbeardman** [comment]
I'm currently generating my own BDF from the TTF using `otf2bdf` but it requires a bit of trial and error to get the sizing correct, which is why I've been trying the Glyphs export.

Parsing the Glyphs format is not something I have time to do, sadly.  Especially when Glyphs + BDF is so close to working. 

@robmeek did you have any thoughts about adding the BDFpixel and grid settings in? That should help all Fontstruct Export users.

**Comment by robmeek** [comment]
@gingerbeardman yes I have thoughts, but I’ll contact you in another way. I don’t think this is the right place for discussing FontStruct exports.

**Comment by schriftgestalt** [comment]
Here is the corrected file and the exported bdf
[becker_bold.zip](https://github.com/schriftgestalt/BDFFileFormat/files/4599099/becker_bold.zip)
I don’t really know if the exported file is valid as I have to way to test. But it looks good to me.

Fontstruct could set the grid correctly (1), but the other settings are too specific. 

1) Probably set the main grid and the subdivision to the same number to not force smaller shapes to the grid.

**Comment by robmeek** [comment]
I’ll add the grid to the export. That looks quite simple (and a cool enhancement!)

**Comment by gingerbeardman** [comment]
Thanks @robmeek 

The BDFpixel setting is an alias to let Glyphs know what you're exporting the pixel as (assuming you don't want to change it away from `brick-1`)

Let me know if you're getting in touch with me another way as I may miss it!

@schriftgestalt your sample exported file is correct - cheers! I use Bits'n'Picas to view the BDF, and bdf2bmp to convert to an image.

**Comment by schriftgestalt** [comment]
@robmeek I see that the original shape is much bigger than the script and the components are scaled down. Is that something that could be changed? 

I think I could change the requirement to know the component name and just export whatever components there are.

**Comment by robmeek** [comment]
@gingerbeardman I'll have to check regarding the names of the brick components – whether there was a logical reason for naming the components in that way, or whether I can use the actual brick names (the pixel brick is called “Pixel”!) without causing problems elsewhere – maybe @schriftgestalt ’s last comment makes this moot anyway.

@schriftgestalt 
> I see that the original shape is much bigger than the script and the components are scaled down. Is that something that could be changed?

Yes theoretically but what advantage would that bring? I would be hesitant to change this because:

- It works as it is!
- There could be a future option in FontStruct to scale components individually rather than just globally – so there would be scaling of each component anyway.
- Isn’t it desirable to have the brick shapes stored at the highest possible “resolution” in the glyphs file and to have rounding errors made at the last stage in the chain of representation. Who knows what wondrous formats, with infinite em squares, Glyphs will be exporting to in the future?

> Let me know if you're getting in touch with me another way as I may miss it!

– maybe not necessary after all, as long as @schriftgestalt doesn’t mind us discussing this here ;-)

**Comment by schriftgestalt** [comment]
We have a pixel tool that can be used to draw pixels. It relies on a glyph called 'pixel' that has the size of the grid (it can be bigger or smaller of cause but it will use it unscaled). Also it would be cleaner if the font would be exported as TrueType.

**Comment by robmeek** [comment]
What I might do then, is make a special case for exporting FontStructions which only include the pixel brick and where the global scaling is 1x1 – in such cases, I would scale the pixel brick instead of every individual component.

**Comment by robmeek** [comment]
I’ve made the discussed changes to the FontStruct glyphs export:

* grid values are now included
* brick glyphs are named less cryptically – the pixel glyph being called “pixel”
* if the FontStruct design is a “pure” pixel font with no scaling and no bricks other than the pixel one, then it will be exported as described above . This seems to work seamlessly with the pixel plugin which is cool.

Maybe you can try it out @gingerbeardman 

PS I couldn’t test this BDF plugin. I was able to install it but I’m getting an error. I suspect the error is specific to my machine though as my Catalina install is pretty messed up.

**Comment by gingerbeardman** [comment]
Looks good to me! 

I did get a BDF plugin error first time, but all subsequent attempts it has exported just fine and BDF file is good for use elsewhere in my workflow.

Thank you very much to both of you. Stay safe and happy font creating!
